---
título: digitalRead()
categorías: [ "Funciones" ]
subCategorías: [ "E/S digitales" ]
---


//
:ext-relativo: .html

= digitalRead()


// COMIENZA LA SECCIÓN VISIÓN GENERAL
[#overview]
--

[float]
=== Descripción
Lee el valor de un pin digital especificado, ya sea `HIGH` o `LOW`.
[%hardbreaks]


[float]
=== Sintaxis
`digitalRead(pin)`


[float]
=== Parámetros
`pin`: el número del pin digital que quieres leer

[float]
=== Devuelve
HIGH` o `LOW

--
// FIN DE LA SECCIÓN




// CÓMO USAR LA SECCIÓN EMPIEZA
[#howtouse]
--

[float]
=== Código de ejemplo
// Describe en qué consiste el código de ejemplo y añade el código relevante ►►►►► ESTA SECCIÓN ES OBLIGATORIA ◄◄◄◄◄
Establece el pin 13 al mismo valor que el pin 7, declarado como entrada.

//[fuente,arduino]
----
int ledPin = 13; // LED conectado al pin digital 13
int inPin = 7; // pulsador conectado al pin digital 7
int val = 0; // variable para almacenar el valor leído

void setup()
{
  pinMode(ledPin, OUTPUT); // establece el pin digital 13 como salida
  pinMode(inPin, INPUT); // establece el pin digital 7 como entrada
}

void loop()
{
  val = digitalRead(inPin); // lee el pin de entrada
  digitalWrite(ledPin, val); // ajusta el LED al valor del botón
}
----
[%hardbreaks]

[float]
=== Notas y Advertencias
Si el pin no está conectado a nada, digitalRead() puede devolver HIGH o LOW (y esto puede cambiar aleatoriamente).

Los pines de entrada analógica pueden ser usados como pines digitales, referidos como A0, A1, etc.

--
// COMO USAR LA SECCION TERMINA


// VER TAMBIÉN SECCIÓN
[#ver_tambien]
--

[float]
=== Véase también

[role="ejemplo"]
* #EXAMPLE# Tutorial: (http://arduino.cc/es/Tutorial/DigitalPins[Digital Pins])

--
// VER TAMBIÉN SECCIÓN EXTREMOS


