---
título: pinMode()
categorías: [ "Funciones" ]
subCategorías: [ "E/S digitales" ]
---


//
:ext-relativo: .html

= pinMode()


// COMIENZA LA SECCIÓN OVERVIEW
[#overview]
--

[float]
=== Descripción
Configura el pin especificado para que se comporte como una entrada o una salida. Ver la descripción de (http://arduino.cc/en/Tutorial/DigitalPins[digital pins]) para más detalles sobre la funcionalidad de los pines.
[%hardbreaks]
A partir de Arduino 1.0.1, es posible habilitar las resistencias pullup internas con el modo INPUT_PULLUP. Además, el modo INPUT desactiva explícitamente los pullups internos.
[%hardbreaks]


[float]
=== Sintaxis
`pinMode(pin, mode)`

[float]
=== Parámetros
`pin`: el número del pin cuyo modo deseas establecer

`mode`: `INPUT`, `OUTPUT`, o `INPUT_PULLUP`. (consulta la página (http://arduino.cc/en/Tutorial/DigitalPins[digital pins]) para una descripción más completa de la funcionalidad).

//Comprueba cómo añadir enlaces

[float]
=== Devuelve
Nada

--
// RESUMEN SECCIÓN TERMINA




// CÓMO USAR LA SECCIÓN COMIENZA
[#cómousar]
--

[float]
=== Código de ejemplo
El código convierte el pin digital 13 en `OUTPUT` y lo alterna entre `HIGH` y `LOW`.

//[fuente,arduino]
----
void setup()
{
  pinMode(13, OUTPUT); // establece el pin digital 13 como salida
}

void loop()
{
  digitalWrite(13, HIGH); // activa el pin digital 13
  delay(1000); // espera un segundo
  digitalWrite(13, LOW); // apaga el pin digital 13
  delay(1000); // espera un segundo
}
----
[%hardbreaks]

[float]
=== Notas y advertencias
Los pines de entrada analógica pueden utilizarse como pines digitales, denominados A0, A1, etc.

--
// CÓMO USAR LA SECCIÓN EXTREMOS


// VER TAMBIÉN SECCIÓN
[#ver_tambien]
--

[float]
=== Véase también

[role="ejemplo"]
* #EXAMPLE# http://arduino.cc/es/Tutorial/DigitalPins[Descripción de los pines en una placa Arduino^]

--
// VER TAMBIÉN SECCIÓN EXTREMOS


