---
título: analogWrite()
categorías: [ "Funciones" ]
subCategorías: [ "E/S Analógicas" ]
---

= analogWrite()

// COMIENZA LA SECCIÓN DE VISTA GENERAL
[#overview]
--

[float]
=== Descripción
Escribe un valor analógico (http://arduino.cc/es/Tutorial/PWM[onda PWM]) en un pin. Puede usarse para encender un LED a diferentes brillos o para accionar un motor a varias velocidades. Después de una llamada a `analogWrite()`, el pin generará una onda cuadrada constante del ciclo de trabajo especificado hasta la siguiente llamada a `analogWrite()` (o una llamada a `digitalRead()` o `digitalWrite()`) en el mismo pin. La frecuencia de la señal PWM en la mayoría de los pines es de aproximadamente 490 Hz. En el Uno y placas similares, los pines 5 y 6 tienen una frecuencia de aproximadamente 980 Hz.
[%hardbreaks]
En la mayoría de las placas Arduino (aquellas con ATmega168 o ATmega328P), esta función funciona en los pines 3, 5, 6, 9, 10 y 11. En el Arduino Mega, funciona en los pines 2 - 13 y 44 - 46. Las placas Arduino más antiguas con un ATmega8 sólo soportan `analogWrite()` en los pines 9, 10 y 11.
El Arduino DUE soporta `analogWrite()` en los pines 2 a 13, además de los pines DAC0 y DAC1. A diferencia de los pines PWM, DAC0 y DAC1 son convertidores de Digital a Analógico, y actúan como verdaderas salidas analógicas.
No es necesario llamar a `pinMode()` para establecer el pin como salida antes de llamar a `analogWrite()`.
La función `analogWrite` no tiene nada que ver con los pines analógicos o la función `analogRead`.
[%hardbreaks]




[float]
=== Sintaxis
`analogWrite(pin, valor)`




[float]
=== Parámetros
`pin`: el pin donde escribir. Tipos de datos permitidos: int. +
`value`: el ciclo de trabajo: entre 0 (siempre apagado) y 255 (siempre encendido). Tipos de datos permitidos: int




[float]
=== Devuelve
Nada


--
// RESUMEN TERMINA LA SECCIÓN








// CÓMO USAR LA SECCIÓN COMIENZA
[#cómousar]
--


[float]
=== Código de ejemplo
Establece la salida al LED proporcional al valor leído del potenciómetro.




[fuente,arduino]
----
int ledPin = 9; // LED conectado al pin digital 9
int analogPin = 3; // potenciómetro conectado al pin analógico 3
int val = 0; // variable para almacenar el valor leído


void setup()
{
  pinMode(ledPin, OUTPUT); // establece el pin como salida
}


void loop()
{
  val = analogRead(analogPin); // lee el pin de entrada
  analogWrite(ledPin, val / 4); // los valores de analogRead van de 0 a 1023, los de analogWrite de 0 a 255
}
----
[%hardbreaks]




[float]
=== Notas y advertencias
Las salidas PWM generadas en los pines 5 y 6 tendrán ciclos de trabajo más altos de lo esperado. Esto es debido a interacciones con las funciones `millis()` y `delay()`, que comparten el mismo temporizador interno usado para generar esas salidas PWM. Esto se notará sobre todo en configuraciones de ciclo de trabajo bajo (p.e. 0 - 10) y puede dar lugar a que un valor de 0 no apague completamente la salida en los pines 5 y 6.


--
// COMO USAR LA SECCION TERMINA




// VER TAMBIÉN SECCIÓN
[#ver_tambien]
--


[float]
=== Véase también


[role="idioma"]
* #LANGUAGE# link:../../zero-due-mkr-family/analogwriteresolution[analogWriteResolution()]


[role="definición"]
* #DEFINITION# http://arduino.cc/es/Tutorial/PWM[PWM^]


[role="ejemplo"]
* #EXAMPLE# http://arduino.cc/es/Tutorial/Blink[Parpadeo^]

--
// VER TAMBIÉN SECCIÓN EXTREMOS
