---
título: analogRead()
categorías: [ "Funciones" ]
subCategorías: [ "E/S Analógicas" ]
---




= analogRead()


// COMIENZA LA SECCIÓN VISIÓN GENERAL
[#overview]
--

[float]
=== Descripción
Lee el valor del pin analógico especificado. La placa Arduino contiene un convertidor analógico-digital de 6 canales (8 canales en el Mini y Nano, 16 en el Mega) y 10 bits. Esto significa que asignará voltajes de entrada entre 0 y 5 voltios a valores enteros entre 0 y 1023. Esto produce una resolución entre lecturas de: 5 voltios / 1024 unidades o, .0049 voltios (4.9 mV) por unidad. El rango de entrada y la resolución pueden cambiarse usando link:../analogreference[analogReference()].

Se tardan unos 100 microsegundos (0,0001 s) en leer una entrada analógica, por lo que la velocidad máxima de lectura es de unas 10.000 veces por segundo.
[%hardbreaks]


[float]
=== Sintaxis

`analogRead(pin)`

[float]
=== Parámetros
`pin`: el número del pin de entrada analógica del que leer (0 a 5 en la mayoría de las placas, 0 a 7 en la Mini y Nano, 0 a 15 en la Mega)

[float]
=== Devuelve
int(0 a 1023)

--
// FIN DE LA SECCIÓN




// CÓMO USAR LA SECCIÓN EMPIEZA
[#cómousar]
--

[float]
=== Código de ejemplo
// Describe en qué consiste el código de ejemplo y añade el código relevante ►►►►► ESTA SECCIÓN ES OBLIGATORIA ◄◄◄◄◄
El código lee el voltaje en analogPin y lo muestra.

[fuente,arduino]
----
int analogPin = 3; // wiper del potenciómetro (terminal central) conectado al pin analógico 3
                       // cables exteriores a masa y +5V
int val = 0; // variable para almacenar el valor leído

void setup()
{
  Serial.begin(9600); // configurar serie
}

void loop()
{
  val = analogRead(analogPin); // lee el pin de entrada
  Serial.println(val); // depurar valor
}
----
[%hardbreaks]

[float]
=== Notas y Advertencias
Si el pin de entrada analógica no está conectado a nada, el valor devuelto por analogRead() fluctuará en función de varios factores (por ejemplo, los valores de las otras entradas analógicas, lo cerca que esté tu mano de la placa, etc.).

--
// COMO USAR LA SECCION TERMINA


// VER TAMBIÉN SECCIÓN
[#ver_tambien]
--

[float]
=== Véase también

[role="idioma"]
* #LANGUAGE# link:../../zero-due-mkr-family/analogreadresolution[analogReadResolution()]
* #LANGUAGE# https://www.arduino.cc/es/Tutorial/AnalogInputPins[Tutorial: Pines de entrada analógica]
--
// VER TAMBIÉN SECCIÓN EXTREMOS
